[profile.default]
src = 'src/contracts'
test = 'test'
out = 'artifacts'
libs = ["node_modules", "lib"]
optimizer = true
optimizer_runs = 100
remappings = [
    '@openzeppelin/=node_modules/@openzeppelin/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat/=node_modules/hardhat/',
    'solmate/=node_modules/solmate/',
]
[fuzz]
runs = 1000
max_test_rejects = 1000000

